#include "src/service/fallback_service.h"

#include "src/ai/openai_compatible_client.h"
#include "src/ai/prompt_builder.h"
#include "src/model/code_object_node.h"
#include "src/model/project_session.h"

FallbackService::FallbackService(ProjectSession &session,
                                 PromptBuilder &promptBuilder,
                                 OpenAiCompatibleClient &aiClient,
                                 QObject *parent)
    : QObject(parent)
    , m_session(session)
    , m_promptBuilder(promptBuilder)
    , m_aiClient(aiClient)
{
}

bool FallbackService::retryNodeWithAi(const QString &nodeId)
{
    const CodeObjectNode *node = m_session.findNodeById(nodeId);
    if (!node) {
        m_session.appendLogLine(tr("[ai] node not found: %1").arg(nodeId));
        return false;
    }

    m_aiClient.reloadFromEnvironment();

    const QString prompt = m_promptBuilder.buildForNode(*node, m_session);
    m_session.setPromptPreviewText(prompt);
    m_session.appendLogLine(tr("[ai] prepared fallback prompt for %1").arg(node->qualifiedName));

    if (!m_aiClient.isConfigured()) {
        m_session.setStatusMessage(tr("AI provider is not configured. Falling back to placeholder source."));
        m_session.appendLogLine(tr("[ai] provider not configured; using placeholder output"));
        return m_session.applyAiResultToNode(nodeId,
                                             buildPlaceholderSource(*node),
                                             CodeObjectNode::Status::AiReconstructed);
    }

    m_session.setStatusMessage(tr("Requesting AI fallback for %1...").arg(node->qualifiedName));
    const AiReconstructionResult result = m_aiClient.reconstruct(node->qualifiedName, prompt);
    if (!result.success) {
        m_session.setStatusMessage(tr("AI fallback failed for %1").arg(node->qualifiedName));
        m_session.appendLogLine(tr("[ai] request failed: %1").arg(result.errorMessage));
        return false;
    }

    m_session.setStatusMessage(tr("AI fallback completed for %1").arg(node->qualifiedName));
    m_session.appendLogLine(tr("[ai] reconstructed %1").arg(node->qualifiedName));
    return m_session.applyAiResultToNode(nodeId,
                                         result.finalSource,
                                         CodeObjectNode::Status::AiReconstructed);
}

QString FallbackService::buildPlaceholderSource(const CodeObjectNode &node) const
{
    QString source;
    source += QStringLiteral("# AI fallback placeholder generated by pycdc-studio\n");
    source += QStringLiteral("# Qualified name: %1\n").arg(node.qualifiedName);
    source += QStringLiteral("# Replace this with the actual model response once an AI provider is connected.\n\n");

    if (node.objectType == QStringLiteral("module")) {
        source += QStringLiteral("# Module-level reconstruction placeholder\n");
        source += QStringLiteral("# TODO: replace with actual AI-reconstructed module source\n");
        return source;
    }

    if (node.objectType == QStringLiteral("class")) {
        source += QStringLiteral("class %1:\n").arg(node.displayName);
        source += QStringLiteral("    pass\n");
        return source;
    }

    const QString functionName = node.displayName.isEmpty() ? QStringLiteral("reconstructed") : node.displayName;
    source += QStringLiteral("def %1(*args, **kwargs):\n").arg(functionName);
    source += QStringLiteral("    # TODO: replace with actual AI-reconstructed source\n");
    source += QStringLiteral("    raise NotImplementedError('AI fallback not connected yet')\n");
    return source;
}
